### ISSUE TITLE
Scraper does not account for thousands in Star/Watcher/Fork count

### ISSUE THREAD

**Issue by gianlucascoccia** [nelsonic/github-scraper#112]
I have found that, for popular repositories with thousands of stars and watchers, the scraper does not provide the correct output, probably as it disregards the 'k' appended after the number.

Take, for instance, the [Atom repository](https://github.com/atom/atom):
<img width="439" alt="Schermata 2020-06-25 alle 08 39 26" src="https://user-images.githubusercontent.com/3214514/85668859-84b9cf80-b6bf-11ea-848d-67c95a189cc0.png">

This is the output provided by my simple script, that just outputs the data received from the scraper:
<img width="748" alt="Schermata 2020-06-25 alle 08 41 24" src="https://user-images.githubusercontent.com/3214514/85669007-af0b8d00-b6bf-11ea-924b-54549f9760bd.png">

**Comment by nelsonic** [comment]
@gianlucascoccia thanks for opening this issue to inform us that the `k` values are no longer working.
As you can see from the screenshot you have kindly shared, the `commits` value is **`NaN`** too ... 😕 

GitHub have very recently updated their UI and changed a bunch of classes 
so our scraper/parser is no longer getting the correct data. #113 

We have a RegEx that parses the **`52.3k`** to **`52300`**:
https://github.com/nelsonic/github-scraper/blob/47d0a460db49b5ea3067ce4eb1d4e6bc27b7f505/lib/utils.js#L2-L16

and it has tests:
https://github.com/nelsonic/github-scraper/blob/47d0a460db49b5ea3067ce4eb1d4e6bc27b7f505/test/utils.test.js#L7-L14

But as I say, GitHub have changed their UI/classes so they have "broken" our scraper. 🤦 
If you want to _help_ fix this by updating the classes in the `repo` file:

https://github.com/nelsonic/github-scraper/blob/47d0a460db49b5ea3067ce4eb1d4e6bc27b7f505/lib/repo.js#L26-L35

A pull request is very much welcome. 
Thanks. ☀️

**Comment by nelsonic** [comment]
fixed. see: https://github.com/nelsonic/github-scraper/actions/runs/7549448498/job/20553449066#step:5:655
