### ISSUE TITLE
data.avatar is undefied

### ISSUE THREAD

**Issue by nedanwr** [nelsonic/github-scraper#114]
The avatar is not getting split due to it being undefined.

**Comment by nelsonic** [comment]
This is related to the recent UI update. #113

**Comment by nedanwr** [comment]
I tried grabbing the src from img tag with .avatar class but that didn't seem to work. Because right now, the avatar is in an img tag with the class of avatar.

**Comment by nelsonic** [comment]
Works again. Ref: https://github.com/nelsonic/github-scraper/actions/runs/7549448498/job/20553449066#step:5:19
