### ISSUE TITLE
Split Problem

### ISSUE THREAD

**Issue by Aurelian123** [nelsonic/github-scraper#115]
var parts = data.avatar.split('-')
                          ^

TypeError: Cannot read property 'split' of undefined

C:\node_modules\github-scraper\lib\profile.js:14

  var parts = data.avatar.split('/');

**Comment by nelsonic** [comment]
Related to #114 & #113

**Comment by nelsonic** [comment]
Fixed. ✅ 
See: https://github.com/nelsonic/github-scraper/actions/runs/7549448498/job/20553449066#step:5:19
