### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by balagpy** [nelsonic/github-scraper#118]
I am getting following error. and kindly give me steps to run. 

 read list of followers for @jupiter (single page of followers) 

      GOT  404  for  {
      headers: {
        Accept: 'text/html',
        'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36'
      },
      hostname: 'github.com',
      port: '443',
      path: '/jupiter/followers'
    } 
      - - - GitHub Scraper SWITCHER FAIL >> /jupiter/followers  - - -  
=============================================================================
Writing coverage object [/Users/balaji/Downloads/github-scraper-master/github-scraper/coverage/coverage.json]
Writing coverage reports at [/Users/balaji/Downloads/github-scraper-master/github-scraper/coverage]
=============================================================================
    =============================== Coverage summary ===============================
    Statements   : 24.17% ( 51/211 )
    Branches     : 20.99% ( 17/81 )
    Functions    : 22.73% ( 5/22 )
    Lines        : 24.17% ( 51/211 )
    ================================================================================
/Users/balaji/Downloads/github-scraper-master/github-scraper/test/followers.test.js:7
    t.equal(data.type, 'followers', username + ' data.type: ' + data.type);
                 ^

TypeError: Cannot read property 'type' of undefined
    at /Users/balaji/Downloads/github-scraper-master/github-scraper/test/followers.test.js:7:18
    at /Users/balaji/Downloads/github-scraper-master/github-scraper/lib/switcher.js:9:2215
    at ClientRequest.<anonymous> (/Users/balaji/Downloads/github-scraper-master/github-scraper/lib/http_request.js:9:991)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:640:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)

**Comment by nelsonic** [comment]
@balagpy thanks for posting this issue. it's related to #113 (the 2020 UI Update)

**Comment by asntc** [comment]
This should be working again. Please test. ✅
