### ISSUE TITLE
Some error for run the github-scraper on google colab page

### ISSUE THREAD

**Issue by soheilpaper** [nelsonic/github-scraper#119]
I have tried to run this repo's java codes on [this colab page](http://colab.research.google.com/github/So-AI-love/Test_NN/blob/main/Statistics/Run_github-scraper_by_java.ipynb#scrollTo=boGfCdYRiCP_) but i get this error:
```
!java  -jar  'get_profile.js' 
Error: Invalid or corrupt jarfile get_profile.js
```
If that colab page could be working, it could be a fast online test for this repo and ...

So i have created this issue to have others help to fix its bugs.

Also asked [here](https://stackoverflow.com/questions/67456608/some-error-for-run-the-github-scraper-on-google-colab-page).
Thanks.

**Comment by asntc** [comment]
Closing as no response. ✅
