### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by ivdnsiz** [nelsonic/github-scraper#120]
I'm getting this issue:
https://github.com/nelsonic/github-scraper/issues/115

**Comment by nelsonic** [comment]
Hey @ivdnsiz thanks for asking. 👋 
Some of the functions still work. ✅ 
but GitHub has kindly updated their UI _again_ 🙄 
so some of the `DOM` elements (`CSS` class names and `IDs`) where changed
which breaks the scraper's parsing. 😢 

PRs very much welcome to fix. 🙏 

I _might_ have time to look at it in the next few weeks but cannot promise anything. Sorry.

**Comment by nelsonic** [comment]
Yes. Updated this week to parse all the UI changes `GitHub` have recently made. ✅ 
Thank you for your interest and opening this issue. 👌
