### ISSUE TITLE
4 failing tests preventing commits on `revive` branch

### ISSUE THREAD

**Issue by iteles** [nelsonic/github-scraper#16]
Currently there are 4 failing tests which fail the pre-commit hook on the `revive` branch.

<img width="606" alt="4-tests-fail" src="https://cloud.githubusercontent.com/assets/4185328/8941167/fe558f90-3565-11e5-9a7d-8f5f90bbf004.png">
<img width="337" alt="description-of-failing-tests" src="https://cloud.githubusercontent.com/assets/4185328/8941168/fe57c972-3565-11e5-86a5-4cc50913de12.png">

These tests are actually no longer relevant to the project!

**Comment by nelsonic** [comment]
Ok. please comment out those tests. 
Saving records to files is #Legacy from last year when I was planning on using the filesystem for storing **Hansel**'s records ...

![hansel he's so hot right now](http://www.lookhuman.com/render/product/8586/8586807606304808/tr401atg-w800h800z1-9225-hansel-hes-so-hot-right-now.jpg)

**Comment by iteles** [comment]
Was using an old version of node, thanks for the tip @nelsonic!

http://www.roisinofarrell.com/wp-content/gallery/cache/693__400x400_homer-doh.gif

Will add to `package.json` :blush:
