### ISSUE TITLE
Should we store *ALL* of the info for each label?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/github-scraper#22]
When we scrape a list of issues we get *all* the styling info for each label every time.
<img width="813" alt="scraper-label-contains-all-info" src="https://cloud.githubusercontent.com/assets/194400/8945688/7863c692-3581-11e5-8a03-d7de765c39ba.png">
We *could* store all the `attribs` for each label, however, this feels like an incredibly wasteful way of storing the data ... could we instead have a labels hash where this data is stored...?
Or ... given that labels and colors are *free text* (and we would thus have collisions where one repo uses red for the "**idea**" (_custom_) label where another repo might use *green* ...

Should we store a hash of all the labels used by a given repo on a per-repo basis?

**Comment by iteles** [comment]
What currently makes most intuitive sense to me is for each repo, to have a list of all the labels plus their (custom) colour (I don't think we need more information than this for the labels, except maybe the total number of issues with this label - though this can be calculated).
Then the issue itself would only have the label name against it and the colour can be looked up based on the repo it's in.

This would keep us from storing duplicate data.

**Comment by nelsonic** [comment]
Labels scraper done: https://github.com/nelsonic/github-scraper/blob/53cdf8c25f0da1eda6e5d2fd3c0a87c2068aa45e/lib/labels.js
which means we only need the *text* of the label when scraping the issue(s)
