### ISSUE TITLE
Is it useful to know all the labels available/used in a given repository?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/github-scraper#23]
Is worth having a list of all the labels used in a repo?

e.g: https://github.com/dwyl/tudo/labels is (_currently_) only using the "*standard*" labels.

<img width="998" alt="github-dwyl-tudo-labels-list" src="https://cloud.githubusercontent.com/assets/194400/8945752/36c87754-3582-11e5-9a46-a4a786ca7c25.png">

Whereas the RethinkDB (which uses GitHub for all their project tracking) uses _several **custom labels**_: 
https://github.com/rethinkdb/rethinkdb/labels

<img width="996" alt="github-rethinkdb-issues-list" src="https://cloud.githubusercontent.com/assets/194400/8945786/7b98b718-3582-11e5-961b-905d268dd39a.png">

**Comment by nelsonic** [comment]
Storing the labels as a separate hash with the color/styles and the number of open issues will mean we only have to store the label **text** in our issues (list) crawler.

**Comment by iteles** [comment]
Agreed, this is also what seems [sensible to me](https://github.com/nelsonic/github-scraper/issues/22#issuecomment-125774535).
