### ISSUE TITLE
Should we collect the info on Milestones?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/github-scraper#29]
e.g: https://github.com/dwyl/tudo/milestones
![github-milestones](https://cloud.githubusercontent.com/assets/194400/9002389/7ca16882-375b-11e5-96f8-e4e383366544.png)

**Comment by iteles** [comment]
I think the due date and completed %age info especially is useful for something like github.com/tudo :+1:

**Comment by nelsonic** [comment]
here's are a couple of milestones with better descriptions:
![dwyl-tudo-milestones](https://cloud.githubusercontent.com/assets/194400/9010055/b3e4da72-379c-11e5-8fd3-680bf928a389.png)
