### ISSUE TITLE
Should we collect info on organisations?

### ISSUE THREAD

**Issue by iteles** [nelsonic/github-scraper#31]
Should we also collect information **from the organisation**, such as how recent the latest updates were (activity trends), how many stars their repos have and the people associated with that organisation? 

It feels like this might be a duplication of data (we can get all of this from the person profiles and the individual repos themselves with some crunching/analysis of the raw data), would it be useful in this format?
<img width="1134" alt="collect-info-from-orgs-for-scraper" src="https://cloud.githubusercontent.com/assets/4185328/9015844/f65ec83c-37c3-11e5-8ee5-ff7db9b8b715.png">

**Comment by nelsonic** [comment]
on it. :+1:
