### ISSUE TITLE
Should we collect info on the trending repos/developers from github?

### ISSUE THREAD

**Issue by iteles** [nelsonic/github-scraper#32]
It seems like Github is doing a decent(ish) job of putting together trending repos and people so it would be a shame to waste this data: https://github.com/trending
<img width="1151" alt="github-trending-repos" src="https://cloud.githubusercontent.com/assets/4185328/9019194/e3cd2378-37df-11e5-86a0-869a89e116a4.png">
<img width="1121" alt="github-trending-developers" src="https://cloud.githubusercontent.com/assets/4185328/9019193/dc0c8aac-37df-11e5-9df4-9b6db8c09e72.png">

This post explains how the trending data comes together: https://github.com/blog/1585-explore-what-is-trending-on-github#questions

**Comment by nelsonic** [comment]
@iteles yes, the trends are interesting, but curated, limited to a handful of people/projects and not queryable ... we still need to source our own data.

**Comment by iteles** [comment]
I _Absolutely_ agree. Using the raw data people can put together the information in a way that's much more interesting for them. 
I was considering it more as an intriguing source of data in that the trajectory of projects and people tagged as once appearing on the trending list might be of interest.     
I'd also originally considered it as a hook for _Hansel_ but  we would actually want him to be more self-reliant than that! :+1:

**Comment by nelsonic** [comment]
It certainly is *interesting* data. 
Much like this list: http://www.wwe.com/classics/classic-lists/top-50-good-guys :wink:
