### ISSUE TITLE
parse state in individual issue

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/github-scraper#39]
parse individual issue state

**Comment by nelsonic** [comment]
@iteles I'm about to start digging into this, do you want to pair? :question: 
we *could* work on *your* computer plugged into the big screen ... :computer: 
let me know in the next 10 mins. :+1:

**Comment by iteles** [comment]
YES!

**Comment by nelsonic** [comment]
OK, I'll go get the Monitor set up. you have 15mins to finish what you're working on now (or get it to a WiP point so you can context-switch ...)

**Comment by nelsonic** [comment]
Really wish you had been interested enough to stay till the end of solving this. 
it required some good old fashioned detective work... :mag:

**Comment by iteles** [comment]
I _was_. We took a break for a rest and when I came to check on you for lunch you were asleep, so I **assumed** you'd let me know when you woke up so we could continue, rather than me waking you up by coming to 'check if you were still asleep' every 30 minutes.
