### ISSUE TITLE
Sketch Simple Crawler Working Diagram

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/github-scraper#44]
relates to #38

**Comment by iteles** [comment]
:+1:  This will be super interesting!

**Comment by nelsonic** [comment]
I'm torn on making the Web Crawler a Private repo ... 
![great responsibility](http://moscowcoffeereview.com/carpecakem/wp-content/uploads/spiderman-responsibility.jpg)

**Comment by nelsonic** [comment]
@iteles this is the simplest diagram I could think of:
![web-crawler-diagram](https://cloud.githubusercontent.com/assets/194400/9045329/3cdf47ca-3a1a-11e5-9178-c2c0da4654a1.jpg)
