### ISSUE TITLE
Issue with some types of user names.

### ISSUE THREAD

**Issue by sAbakumoff** [nelsonic/github-scraper#60]
```javascript
scrapper('hangouts/followers', function(err, data){
  console.log(err);
});
```
produces
 - - - GitHub Scraper SWITCHER FAIL >> https://github.comhangouts/followers  - - - 
404

However, this user does exist : https://github.com/hangouts/followers

**Comment by nelsonic** [comment]
@sAbakumoff well spotted! thanks for posting this issue. I will look into why the switcher is failing. :+1:

**Comment by nelsonic** [comment]
Ah... I must have coded this when I was *very* tired... thanks for *highlighting* this. :+1: 
The `url_validator` was meant to check for urls beginning in `http` or `https` but instead only checked for the character `h` ... duh...!

**Comment by nelsonic** [comment]
@sAbakumoff see latest version on NPM. :+1:
