### ISSUE TITLE
Best way to scrape all issues (or followers, ...)

### ISSUE THREAD

**Issue by pkofod** [nelsonic/github-scraper#68]
What is the best way to scrape all issues? Using followers instead, you suggest in the manual to

```js
var url = 'alanshaw/followers' // a random username (of someone you should follow!)
gs(url, function(err, data) {
  console.log(data); // or what ever you want to do with the data
  if(data.next_page) {
    gs(data.next_page, function(err2, data2)) {
      console.log(data2); // etc.
    }
  }
})
```
but what about page 3, 4, ...?

**Comment by nelsonic** [comment]
@pkofod well spotted those docs are incorrect. 
The way I've implemented this is with a **Redis Queue** not a nested call...
if you're interested checkout: https://github.com/nelsonic/arana

**Comment by pkofod** [comment]
Great, will look! Thanks
