### ISSUE TITLE
data.contribs not parsing correctly

### ISSUE THREAD

**Issue by avilano** [nelsonic/github-scraper#72]
Tried to use the example from the readme:

```
router.post('/', function(req, res, next){
  var url = '/iteles' // a random username
  gs(url, function(err, data) {
    console.log(data); // or what ever you want to do with the data
  })
});
```

<img width="994" alt="screen shot 2016-08-31 at 1 46 59 pm" src="https://cloud.githubusercontent.com/assets/20048240/18142074/90d051ba-6f81-11e6-8969-db130e1def5a.png">

**Comment by nelsonic** [comment]
@avilano yeah, we need to update for the latest GitHub UI... 😞

**Comment by nelsonic** [comment]
Contribs working: https://github.com/nelsonic/github-scraper/actions/runs/7549448498/job/20553449066#step:5:38
