### ISSUE TITLE
Getting email (if available) from list of followers for a thank you msg

### ISSUE THREAD

**Issue by Rob-Rychs** [nelsonic/github-scraper#89]
Hey @nelsonic,

Since github api no longer sends out events on new follows I was trying to get emails from my list of followers but it doesn't seem to be working... it probably thinks I'm up to no good

```JS
data.email    = $('.u-email').text(); // this comes out blank
data.email    = $('.u-email').attr('href'); // this comes out undefined
data.email    = $('.octicon-email').parent().text(); // this comes out blank
```

I suppose this is obfuscated somehow? Any work-arounds that you know of? Not asking for use in spaming
<b>Regards

**Comment by nelsonic** [comment]
@Rob-Rychs indeed, GitHub no longer makes email addresses public on people's profiles.
Sadly, you're out-of-luck. 😞 
There _is_ a way to get a person's email address via the API but it requires Auth. 👍

**Comment by Rob-Rychs** [comment]
Thanks I'll take a look at API
